---
- name: Create a virtual machine a vCenter
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ folder_path }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    state: present
    guest_id: ubuntu64Guest
    template: "{{ template }}"
    disk:
      - size_gb: 64
        type: thin
        datastore: "{{ datastore_name }}"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
    networks:
      - name: "Server (13)"
        type: "dhcp"
        device_type: vmxnet3
        connected: true
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 180
    customization:
      hostname: "{{ vm_name }}"
      domain: "{{ guest_domain }}"
      dns_servers:
        - "{{ guest_dns_server1 }}"
        - "{{ guest_dns_server2 }}"
      dns_suffix:
        - "{{ guest_domain_name1 }}"
        - "{{ guest_domain_name2 }}"
      timezone: "America/Los_Angeles"
  delegate_to: localhost
