---
- name: debug vars
  debug:
    var: vmware

- name: Create a virtual machine a vCenter
  community.vmware.vmware_guest:
    hostname: "{{ host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ folder_path }}"
    name: "{{ vm_name }}"
    state: poweredon
    guest_id: ubuntu64Guest
    disk:
      size_gb: 64
      type: thin
      datastore: "{{ datastore_name }}"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
    networks:
      name: "{{ network_name }}"
      ip: "{{ ipv4_addr }}"
      netmask: 255.255.255.0
      device_type: vmxnet3
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 600
  delegate_to: localhost
  register: deployed_vm
