---
- name: Create a virtual machine a vCenter
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ folder_path }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    state: present
    guest_id: ubuntu64Guest
    disk:
      - size_gb: 64
        type: thin
        datastore: "{{ datastore_name }}"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
  delegate_to: localhost
  register: deployed_vm

- name: "Sleep for 30 seconds"
  ansible.builtin.pause module:
    seconds: 30

- name: Remove a virtual machine from inventory
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    name: "{{ vm_name }}"
    delete_from_inventory: true
    state: absent
  delegate_to: localhost
