---
- name: Set powerstate of a virtual machine to poweroff by using name
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    name: "{{ ansible_hostname }}"
    state: poweredoff
  delegate_to: localhost

- name: Remove a virtual machine from inventory
  community.vmware.vmware_guest:
    hostname: "{{ vmware.host }}"
    username: "{{ vmware.username }}"
    password: "{{ vmware.password }}"
    name: "{{ ansible_hostname }}"
    delete_from_inventory: false
    state: absent
  delegate_to: localhost
